# Generated by Django 4.2.7 on 2023-11-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Narasaraopet', 'Narasaraopet'), ('Guntur', 'Guntur'), ('Vijayawada', 'Vijayawada')], max_length=50)),
            ],
        ),
    ]
