# Generated by Django 4.2.7 on 2023-11-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wether', '0002_remove_data_location_data_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='hours',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
