# Generated by Django 3.2.20 on 2023-11-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wether', '0004_remove_data_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AddField(
            model_name='data',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='locations',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
