# Generated by Django 4.0 on 2024-05-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wether', '0005_auto_20231111_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='crop_type',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='time_frame',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
