# Generated by Django 4.0 on 2024-05-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wether', '0006_data_crop_type_data_time_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(default=False, max_length=50)),
                ('time_frame', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='data',
            name='time_frame',
        ),
    ]
