# Generated by Django 4.0 on 2024-05-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wether', '0007_croptype_remove_data_crop_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='crop_type',
            field=models.CharField(choices=[('paddy', 'Paddy'), ('chilli', 'Chilli'), ('cotton', 'Cotton'), ('corn', 'Corn')], default='paddy', max_length=50),
        ),
    ]
