# Generated by Django 4.0 on 2024-05-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wether', '0008_alter_croptype_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='time_frame',
            field=models.IntegerField(),
        ),
    ]
